language: cpp
compiler:
  - gcc
before_install:
before_script:
    - mkdir build && cd build && cmake ../src
script: make
branches:
notifications:
  recipients:
    - git@aas.io
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#projectchrono"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
env:
